### ISSUE TITLE
Error of using prior datasets

### ISSUE THREAD

**Issue by claywlin** [FZJ-IEK3-VSA/glaes#11]
Hi there, I came across an error when I tried to use GLAES with prior datasets. I have downloaded the priord data from Mendeley Data and unzipping the files into the repo directory glaes/data/priors, but it sitll shows the error as the attachment. Could you please tell me how to solve this problem?

![prior error](https://github.com/FZJ-IEK3-VSA/glaes/assets/127121016/3d137a13-3325-4d2c-bb14-ef8c55408b53)
![image](https://github.com/FZJ-IEK3-VSA/glaes/assets/127121016/907abf0c-f3f5-4253-aeac-66622832c81e)

**Comment by Lillynator** [comment]
Currently trying to make the "create priors function" working again. The working directory for that is "create_priors0.py".  Two test functions were set up, but the first one is not working yet. Issue is further documented in the "create_prior0.py" scipt

**Comment by julian-belina** [comment]
@Lillynator, please let me know when the issue has been resolved, so that I can re-add the test to the pipeline.

**Comment by Lillynator** [comment]
Still in progess. There are a lot of comments in the code itself with the #TODO
Next: evaluate_tif_by_proximity is working now, but results have to be checked (not sure rather the results are valid).
Then: evaluate_tif_by_threshold. Make the function running and test it

**Comment by Lillynator** [comment]
The evaluate_tif_by_proximity function is working but has to be cleaned up!
Next: Debug the other function "evaluate_tif_by_threshold".

More documentation in the create_priors_0.py

**Comment by Lillynator** [comment]
Proximity and Threshold function working. For proximity function working with raster and shape data is implemented but needs to be tested and improved. 
After that: merging the proximity  functions together and clean up.

**Comment by Lillynator** [comment]
Both functions working with shp and tif files. 

Next: 
- cleaning up the functions and doc strings
- deleting the create prior example or create a new one

**Comment by Lillynator** [comment]
TODO:
Writing an example with:
-create prior
-exclude prior

-test against the original exclusion workflow


started with this in Examples/prior_example.ipynb

**Comment by Lillynator** [comment]
the current create_priors_0.py are not running again!

TODO:
-> check whats wrong with running create priors. First step: fix paths.

-> when create priors is running: using shapes within the proximity function needs to be integrated (see severins prior roads example)

-> if that is done: write an example and compare the outputs:
   -> create prior
  -> exclude prior
  -> check rather they are the same as the normal exclude roads results

**Comment by Lillynator** [comment]
The code now generates raster datasets using:
evaluate_area_by_threshold
evaluate_area_by_proximity

Both codes can be run with shape or TIF files as input. 

**TODO's code:**

- [x] Test the where function --> what if only a single polygon is read in rather than an entire shape; does it work?
- [x] Note that functions only make sense for inputs that have an SRS with metric resolution rather than degrees. --> Should check at the start whether the input SRS of tif_target is metric
- [x] Message stating that thresholds must match the pixel size. --> If raster pixel size is 100m, threshold in 100m increments
- [ ] Add or remove print statements where appropriate --> Are any further print statements useful?
- [ ] Are any further error messages needed? --> Where could the process fail = error message

**Further TODOs:**

- [ ] Check with Chris whether rasters can be converted to TIF it:
```
 raster_1 = gk.raster.loadRaster(Area)
        raster_matrix = gk.raster.extractMatrix(raster_1)
        # boolean raster
        ras_boolean = gk.raster.createRasterLike(source=raster_1, data=raster_matrix == 1, noData=0)
```

- [ ] generally check again whether rasters and shapes are being read in and converted correctly


**Further issues:**

- [ ]  adapt the example so that priors are generated first and then applied
- [ ] remove “use priors” from the old example where it fails
- [ ] write tests to test the “create priors” functions

**Comment by Lillynator** [comment]
TODO
- [ ] adapt evaluate_area_by_proximity_shape so that target_file can be a shape instead of a raster file
- [ ] adapt evaluate_area_by_threshold_shape so that target_file can be a shape instead of a raster file

1. The raster SRS is loaded: change to SHP, which is loaded as a mask and the SRS is extracted
2. Shapefile or raster is loaded as an area (remains); the raster’s SRS is used. Must be changed to the SRS from the region mask
3. Raster is loaded, values extracted and converted to a region mask. This needs to be adjusted: instead of the raster, a shapefile is loaded (with featureID) and converted to a region mask

Further issues:
- [ ] adapt the example so that priors are generated first and then applied
- [ ] remove “use priors” from the old example where it fails
- [ ] write tests to test the “create priors” functions
- [ ] Currently it is al int8. limiting number of thresholds. Needs to be discussed with chris

**Comment by Lillynator** [comment]
-  debugger macht manchmal probleme used env ==> glaes_2026
-  four functions work based on the area being passed as either a shapefile or a GeoTIFF
-  targets are passed as GeoTIFFs
- 
- for proximity, it is important that a shapefile can be passed as the target instead of a raster, allowing buffers to be generated around it
- the function handling both cases is named "evaluate_area_by_proximity" (accepting area and target as either shapefile or GeoTIFF)
- this is not relevant for the threshold function, as that involves marking values ​​above or below a certain level (which makes no sense for shapefiles, as they lack cell values)
- 
# TODO:
- the function is not yet operational because loading the region requires the target's dimensions (GeoTIFF/shapefile), but these are currently loaded afterwards. --> `srs_target` and `pixel_res` are missing; these need to be integrated.
- --> solution: load the target's SRS and pixel size first, then load the area to create the region mask, and finally load the targets using that region mask.
- prior creation and prior application example

**Comment by t-cronenberg** [comment]
**Current status:**

- proximity_evaluation_plotting.ipynb: Run and plot the “create prior” functions
- create_priors_0.py: Functions for setting up the priors

 
**current TODO:** 

- “create prior by proximity” should accept not only raster data as an exclusion but also a shapefile. This still needs to be adjusted. The test function for this is: “evaluate_area_by_proximity”

 
**Following steps (or possible additional Issues):** 

- Fix the “int 8” error when proximities are > 200. (Note: The “no data” values must also be adjusted here)
- Docstrings must be adapted to the provided documents
- Remove the figure.png debugging prints from "evaluate_area_by_threshold"
- Adapt the example: “prior_example”—here, an exclusion should first be created using the traditional method. In comparison, a prior should be generated and used for exclusion
- Write tests for all function
